# Setup
title:               robmsmt
tagline:             'curious speech'
description:         'A reserved space for random ramblings!'
url:                 "http://robmsmt.github.io" 
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              robmsmt
  url:               https://twitter.com/robmsmt
  email:             robmsmt@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
